### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B

### method
stage: sft
do_train: true
compute_accuracy: true
finetuning_type: lora
lora_target: all
lora_rank: 32 #32
lora_alpha: 16
lora_dropout: 0.1

### dataset
dataset: train
template: qwen
cutoff_len: 1028
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

# output
output_dir: factory_qwen_results
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4 #3.0e-4
num_train_epochs: 8.0
lr_scheduler_type: cosine #constant
warmup_ratio: 0.03 #0.03
ddp_timeout: 1800
ddp_backend: nccl
bf16: true
resume_from_checkpoint: null

### evaluate
eval_dataset: test
per_device_eval_batch_size: 2
eval_strategy: epoch
# eval_steps: 100