### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 16
lora_dropout: 0.1

### dataset
dataset: train.json
template: qwen2_vl
cutoff_len: 1028
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 12
dataloader_num_workers: 3

# output
output_dir: results/llamafactory/qwen
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 3.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine #constant
warmup_ratio: 0.03
ddp_timeout: 180000000000
bf16: true
resume_from_checkpoint: null